[project]
name = "delta-lake-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deltalake>=1.2.1",
    "pathling>=9.0.0",
    "polars>=1.35.2",
]
